spring:
  application:
    name: eureka-server

server:
  port: 8000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
  client:
    #register-with-eureka:  false
    fetch-registry:  false
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:${server.port}/eureka/
