server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/raoshaoquan/spring-cloud-study/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 32005235@qq.com                                            # git仓库的账号
          password: ztgame@123                                            # git仓库的密码